[project]
name = "CIPHER-raspberry-client"
version = "0.1.0"
description = "Add a short description here"
authors = ["valorun <ronan@collier-famille.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"

[pypi-dependencies]
wiringpi = "*"
pyserial = "*"
paho-mqtt = "*"
adafruit-circuitpython-servokit = "*"
